// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: lookup.proto

package lookuppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lookup_ResolveBIC_FullMethodName  = "/switch.v1.Lookup/ResolveBIC"
	Lookup_SearchBanks_FullMethodName = "/switch.v1.Lookup/SearchBanks"
)

// LookupClient is the client API for Lookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LookupClient interface {
	// Resolve a BIC to bank information.
	ResolveBIC(ctx context.Context, in *BICRequest, opts ...grpc.CallOption) (*BICResponse, error)
	// Search banks by name or country.
	SearchBanks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type lookupClient struct {
	cc grpc.ClientConnInterface
}

func NewLookupClient(cc grpc.ClientConnInterface) LookupClient {
	return &lookupClient{cc}
}

func (c *lookupClient) ResolveBIC(ctx context.Context, in *BICRequest, opts ...grpc.CallOption) (*BICResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BICResponse)
	err := c.cc.Invoke(ctx, Lookup_ResolveBIC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookupClient) SearchBanks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Lookup_SearchBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LookupServer is the server API for Lookup service.
// All implementations must embed UnimplementedLookupServer
// for forward compatibility.
type LookupServer interface {
	// Resolve a BIC to bank information.
	ResolveBIC(context.Context, *BICRequest) (*BICResponse, error)
	// Search banks by name or country.
	SearchBanks(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedLookupServer()
}

// UnimplementedLookupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLookupServer struct{}

func (UnimplementedLookupServer) ResolveBIC(context.Context, *BICRequest) (*BICResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveBIC not implemented")
}
func (UnimplementedLookupServer) SearchBanks(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBanks not implemented")
}
func (UnimplementedLookupServer) mustEmbedUnimplementedLookupServer() {}
func (UnimplementedLookupServer) testEmbeddedByValue()                {}

// UnsafeLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LookupServer will
// result in compilation errors.
type UnsafeLookupServer interface {
	mustEmbedUnimplementedLookupServer()
}

func RegisterLookupServer(s grpc.ServiceRegistrar, srv LookupServer) {
	// If the following call panics, it indicates UnimplementedLookupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lookup_ServiceDesc, srv)
}

func _Lookup_ResolveBIC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BICRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookupServer).ResolveBIC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lookup_ResolveBIC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookupServer).ResolveBIC(ctx, req.(*BICRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lookup_SearchBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookupServer).SearchBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lookup_SearchBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookupServer).SearchBanks(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lookup_ServiceDesc is the grpc.ServiceDesc for Lookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Lookup",
	HandlerType: (*LookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveBIC",
			Handler:    _Lookup_ResolveBIC_Handler,
		},
		{
			MethodName: "SearchBanks",
			Handler:    _Lookup_SearchBanks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lookup.proto",
}
