// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: lookup.proto

package lookuppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BICRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bic           string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BICRequest) Reset() {
	*x = BICRequest{}
	mi := &file_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BICRequest) ProtoMessage() {}

func (x *BICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BICRequest.ProtoReflect.Descriptor instead.
func (*BICRequest) Descriptor() ([]byte, []int) {
	return file_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *BICRequest) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

type BICResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Bic                 string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country             string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	SupportedCurrencies []string               `protobuf:"bytes,4,rep,name=supported_currencies,json=supportedCurrencies,proto3" json:"supported_currencies,omitempty"`
	RoutingInfo         string                 `protobuf:"bytes,5,opt,name=routing_info,json=routingInfo,proto3" json:"routing_info,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BICResponse) Reset() {
	*x = BICResponse{}
	mi := &file_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BICResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BICResponse) ProtoMessage() {}

func (x *BICResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BICResponse.ProtoReflect.Descriptor instead.
func (*BICResponse) Descriptor() ([]byte, []int) {
	return file_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *BICResponse) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *BICResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BICResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *BICResponse) GetSupportedCurrencies() []string {
	if x != nil {
		return x.SupportedCurrencies
	}
	return nil
}

func (x *BICResponse) GetRoutingInfo() string {
	if x != nil {
		return x.RoutingInfo
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_lookup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lookup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_lookup_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BICResponse         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_lookup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lookup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_lookup_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*BICResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_lookup_proto protoreflect.FileDescriptor

const file_lookup_proto_rawDesc = "" +
	"\n" +
	"\flookup.proto\x12\tswitch.v1\"\x1e\n" +
	"\n" +
	"BICRequest\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\"\xa3\x01\n" +
	"\vBICResponse\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x121\n" +
	"\x14supported_currencies\x18\x04 \x03(\tR\x13supportedCurrencies\x12!\n" +
	"\frouting_info\x18\x05 \x01(\tR\vroutingInfo\"\\\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"B\n" +
	"\x0eSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.switch.v1.BICResponseR\aresults2\x89\x01\n" +
	"\x06Lookup\x12;\n" +
	"\n" +
	"ResolveBIC\x12\x15.switch.v1.BICRequest\x1a\x16.switch.v1.BICResponse\x12B\n" +
	"\vSearchBanks\x12\x18.switch.v1.SearchRequest\x1a\x19.switch.v1.SearchResponseB\"Z switch/api/proto/lookup;lookuppbb\x06proto3"

var (
	file_lookup_proto_rawDescOnce sync.Once
	file_lookup_proto_rawDescData []byte
)

func file_lookup_proto_rawDescGZIP() []byte {
	file_lookup_proto_rawDescOnce.Do(func() {
		file_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lookup_proto_rawDesc), len(file_lookup_proto_rawDesc)))
	})
	return file_lookup_proto_rawDescData
}

var file_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lookup_proto_goTypes = []any{
	(*BICRequest)(nil),     // 0: switch.v1.BICRequest
	(*BICResponse)(nil),    // 1: switch.v1.BICResponse
	(*SearchRequest)(nil),  // 2: switch.v1.SearchRequest
	(*SearchResponse)(nil), // 3: switch.v1.SearchResponse
}
var file_lookup_proto_depIdxs = []int32{
	1, // 0: switch.v1.SearchResponse.results:type_name -> switch.v1.BICResponse
	0, // 1: switch.v1.Lookup.ResolveBIC:input_type -> switch.v1.BICRequest
	2, // 2: switch.v1.Lookup.SearchBanks:input_type -> switch.v1.SearchRequest
	1, // 3: switch.v1.Lookup.ResolveBIC:output_type -> switch.v1.BICResponse
	3, // 4: switch.v1.Lookup.SearchBanks:output_type -> switch.v1.SearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lookup_proto_init() }
func file_lookup_proto_init() {
	if File_lookup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lookup_proto_rawDesc), len(file_lookup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lookup_proto_goTypes,
		DependencyIndexes: file_lookup_proto_depIdxs,
		MessageInfos:      file_lookup_proto_msgTypes,
	}.Build()
	File_lookup_proto = out.File
	file_lookup_proto_goTypes = nil
	file_lookup_proto_depIdxs = nil
}
