apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: payment-switch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: payment-switch/audit-service:latest
          envFrom:
            - configMapRef:
                name: payment-switch-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
