apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-switch-config
  namespace: payment-switch
data:
  POSTGRES_DSN: "postgres://switch:switch@postgres:5432/switch?sslmode=disable"
  KAFKA_BROKERS: "redpanda:9092"
  REDIS_ADDR: "redis:6379"
  HTTP_ADDR: ":8080"
