// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: orchestrator.proto

package orchestratorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	payment "switch/api/proto/payment"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_SubmitPayment_FullMethodName     = "/switch.v1.Orchestrator/SubmitPayment"
	Orchestrator_GetPaymentStatus_FullMethodName  = "/switch.v1.Orchestrator/GetPaymentStatus"
	Orchestrator_ListPayments_FullMethodName      = "/switch.v1.Orchestrator/ListPayments"
	Orchestrator_CompensatePayment_FullMethodName = "/switch.v1.Orchestrator/CompensatePayment"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Submit a payment through the saga (RECEIVED → COMMITTED or ABORTED).
	SubmitPayment(ctx context.Context, in *payment.PaymentRequest, opts ...grpc.CallOption) (*payment.PaymentResponse, error)
	// Get the current status of a payment.
	GetPaymentStatus(ctx context.Context, in *payment.StatusRequest, opts ...grpc.CallOption) (*payment.PaymentResponse, error)
	// List payments in a given status (pagination stub).
	ListPayments(ctx context.Context, in *ListPaymentsRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error)
	// Trigger compensation for an existing payment.
	CompensatePayment(ctx context.Context, in *CompensateRequest, opts ...grpc.CallOption) (*CompensateResponse, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) SubmitPayment(ctx context.Context, in *payment.PaymentRequest, opts ...grpc.CallOption) (*payment.PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(payment.PaymentResponse)
	err := c.cc.Invoke(ctx, Orchestrator_SubmitPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetPaymentStatus(ctx context.Context, in *payment.StatusRequest, opts ...grpc.CallOption) (*payment.PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(payment.PaymentResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ListPayments(ctx context.Context, in *ListPaymentsRequest, opts ...grpc.CallOption) (*ListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentsResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ListPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) CompensatePayment(ctx context.Context, in *CompensateRequest, opts ...grpc.CallOption) (*CompensateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompensateResponse)
	err := c.cc.Invoke(ctx, Orchestrator_CompensatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
type OrchestratorServer interface {
	// Submit a payment through the saga (RECEIVED → COMMITTED or ABORTED).
	SubmitPayment(context.Context, *payment.PaymentRequest) (*payment.PaymentResponse, error)
	// Get the current status of a payment.
	GetPaymentStatus(context.Context, *payment.StatusRequest) (*payment.PaymentResponse, error)
	// List payments in a given status (pagination stub).
	ListPayments(context.Context, *ListPaymentsRequest) (*ListPaymentsResponse, error)
	// Trigger compensation for an existing payment.
	CompensatePayment(context.Context, *CompensateRequest) (*CompensateResponse, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) SubmitPayment(context.Context, *payment.PaymentRequest) (*payment.PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPayment not implemented")
}
func (UnimplementedOrchestratorServer) GetPaymentStatus(context.Context, *payment.StatusRequest) (*payment.PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentStatus not implemented")
}
func (UnimplementedOrchestratorServer) ListPayments(context.Context, *ListPaymentsRequest) (*ListPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPayments not implemented")
}
func (UnimplementedOrchestratorServer) CompensatePayment(context.Context, *CompensateRequest) (*CompensateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompensatePayment not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_SubmitPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payment.PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).SubmitPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_SubmitPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).SubmitPayment(ctx, req.(*payment.PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payment.StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetPaymentStatus(ctx, req.(*payment.StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ListPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListPayments(ctx, req.(*ListPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_CompensatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompensateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CompensatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CompensatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CompensatePayment(ctx, req.(*CompensateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPayment",
			Handler:    _Orchestrator_SubmitPayment_Handler,
		},
		{
			MethodName: "GetPaymentStatus",
			Handler:    _Orchestrator_GetPaymentStatus_Handler,
		},
		{
			MethodName: "ListPayments",
			Handler:    _Orchestrator_ListPayments_Handler,
		},
		{
			MethodName: "CompensatePayment",
			Handler:    _Orchestrator_CompensatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
