// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_RECEIVED                   PaymentStatus = 1
	PaymentStatus_VALIDATED                  PaymentStatus = 2
	PaymentStatus_QUOTED                     PaymentStatus = 3
	PaymentStatus_SCREENED                   PaymentStatus = 4
	PaymentStatus_RESERVED                   PaymentStatus = 5
	PaymentStatus_COMMITTED                  PaymentStatus = 6
	PaymentStatus_ABORTED                    PaymentStatus = 7
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "RECEIVED",
		2: "VALIDATED",
		3: "QUOTED",
		4: "SCREENED",
		5: "RESERVED",
		6: "COMMITTED",
		7: "ABORTED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"RECEIVED":                   1,
		"VALIDATED":                  2,
		"QUOTED":                     3,
		"SCREENED":                   4,
		"RESERVED":                   5,
		"COMMITTED":                  6,
		"ABORTED":                    7,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type Payment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndToEndId     string                 `protobuf:"bytes,2,opt,name=end_to_end_id,json=endToEndId,proto3" json:"end_to_end_id,omitempty"`
	SourceBic      string                 `protobuf:"bytes,3,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestinationBic string                 `protobuf:"bytes,4,opt,name=destination_bic,json=destinationBic,proto3" json:"destination_bic,omitempty"`
	SourceAccount  string                 `protobuf:"bytes,5,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	DestAccount    string                 `protobuf:"bytes,6,opt,name=dest_account,json=destAccount,proto3" json:"dest_account,omitempty"`
	Amount         int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`    // minor units (cents)
	Currency       string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`     // PaymentStatus enum value
	QuoteId        *string                `protobuf:"bytes,10,opt,name=quote_id,json=quoteId,proto3,oneof" json:"quote_id,omitempty"`
	ReservedAt     *string                `protobuf:"bytes,11,opt,name=reserved_at,json=reservedAt,proto3,oneof" json:"reserved_at,omitempty"` // RFC 3339
	ExpiresAt      *string                `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`    // RFC 3339
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // RFC 3339
	UpdatedAt      string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // RFC 3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetEndToEndId() string {
	if x != nil {
		return x.EndToEndId
	}
	return ""
}

func (x *Payment) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *Payment) GetDestinationBic() string {
	if x != nil {
		return x.DestinationBic
	}
	return ""
}

func (x *Payment) GetSourceAccount() string {
	if x != nil {
		return x.SourceAccount
	}
	return ""
}

func (x *Payment) GetDestAccount() string {
	if x != nil {
		return x.DestAccount
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetQuoteId() string {
	if x != nil && x.QuoteId != nil {
		return *x.QuoteId
	}
	return ""
}

func (x *Payment) GetReservedAt() string {
	if x != nil && x.ReservedAt != nil {
		return *x.ReservedAt
	}
	return ""
}

func (x *Payment) GetExpiresAt() string {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type PaymentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	EndToEndId    string                 `protobuf:"bytes,2,opt,name=end_to_end_id,json=endToEndId,proto3" json:"end_to_end_id,omitempty"`
	FromStatus    string                 `protobuf:"bytes,3,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus      string                 `protobuf:"bytes,4,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	SourceBic     string                 `protobuf:"bytes,5,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestBic       string                 `protobuf:"bytes,6,opt,name=dest_bic,json=destBic,proto3" json:"dest_bic,omitempty"`
	Amount        int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     string                 `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC 3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentEvent) Reset() {
	*x = PaymentEvent{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEvent) ProtoMessage() {}

func (x *PaymentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEvent.ProtoReflect.Descriptor instead.
func (*PaymentEvent) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentEvent) GetEndToEndId() string {
	if x != nil {
		return x.EndToEndId
	}
	return ""
}

func (x *PaymentEvent) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *PaymentEvent) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *PaymentEvent) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *PaymentEvent) GetDestBic() string {
	if x != nil {
		return x.DestBic
	}
	return ""
}

func (x *PaymentEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentEvent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EndToEndId     string                 `protobuf:"bytes,1,opt,name=end_to_end_id,json=endToEndId,proto3" json:"end_to_end_id,omitempty"`
	DestinationBic string                 `protobuf:"bytes,2,opt,name=destination_bic,json=destinationBic,proto3" json:"destination_bic,omitempty"`
	DestAccount    string                 `protobuf:"bytes,3,opt,name=dest_account,json=destAccount,proto3" json:"dest_account,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ParticipantId  string                 `protobuf:"bytes,6,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentRequest) GetEndToEndId() string {
	if x != nil {
		return x.EndToEndId
	}
	return ""
}

func (x *PaymentRequest) GetDestinationBic() string {
	if x != nil {
		return x.DestinationBic
	}
	return ""
}

func (x *PaymentRequest) GetDestAccount() string {
	if x != nil {
		return x.DestAccount
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\tswitch.v1\"\xee\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\rend_to_end_id\x18\x02 \x01(\tR\n" +
	"endToEndId\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x03 \x01(\tR\tsourceBic\x12'\n" +
	"\x0fdestination_bic\x18\x04 \x01(\tR\x0edestinationBic\x12%\n" +
	"\x0esource_account\x18\x05 \x01(\tR\rsourceAccount\x12!\n" +
	"\fdest_account\x18\x06 \x01(\tR\vdestAccount\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1e\n" +
	"\bquote_id\x18\n" +
	" \x01(\tH\x00R\aquoteId\x88\x01\x01\x12$\n" +
	"\vreserved_at\x18\v \x01(\tH\x01R\n" +
	"reservedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\f \x01(\tH\x02R\texpiresAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAtB\v\n" +
	"\t_quote_idB\x0e\n" +
	"\f_reserved_atB\r\n" +
	"\v_expires_at\"\x9a\x02\n" +
	"\fPaymentEvent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12!\n" +
	"\rend_to_end_id\x18\x02 \x01(\tR\n" +
	"endToEndId\x12\x1f\n" +
	"\vfrom_status\x18\x03 \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\x04 \x01(\tR\btoStatus\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x05 \x01(\tR\tsourceBic\x12\x19\n" +
	"\bdest_bic\x18\x06 \x01(\tR\adestBic\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\tR\ttimestamp\"\xda\x01\n" +
	"\x0ePaymentRequest\x12!\n" +
	"\rend_to_end_id\x18\x01 \x01(\tR\n" +
	"endToEndId\x12'\n" +
	"\x0fdestination_bic\x18\x02 \x01(\tR\x0edestinationBic\x12!\n" +
	"\fdest_account\x18\x03 \x01(\tR\vdestAccount\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0eparticipant_id\x18\x06 \x01(\tR\rparticipantId\"9\n" +
	"\x0fPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1f\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*\x90\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bRECEIVED\x10\x01\x12\r\n" +
	"\tVALIDATED\x10\x02\x12\n" +
	"\n" +
	"\x06QUOTED\x10\x03\x12\f\n" +
	"\bSCREENED\x10\x04\x12\f\n" +
	"\bRESERVED\x10\x05\x12\r\n" +
	"\tCOMMITTED\x10\x06\x12\v\n" +
	"\aABORTED\x10\aB$Z\"switch/api/proto/payment;paymentpbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),      // 0: switch.v1.PaymentStatus
	(*Payment)(nil),         // 1: switch.v1.Payment
	(*PaymentEvent)(nil),    // 2: switch.v1.PaymentEvent
	(*PaymentRequest)(nil),  // 3: switch.v1.PaymentRequest
	(*PaymentResponse)(nil), // 4: switch.v1.PaymentResponse
	(*StatusRequest)(nil),   // 5: switch.v1.StatusRequest
}
var file_payment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_payment_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
