-- Seed data for local development / demo.
-- All statements are idempotent (ON CONFLICT DO NOTHING).

-- ---------------------------------------------------------------------------
-- Banks
-- Each bank corresponds to a participant registered in the gateway's in-memory
-- registry and a mTLS client certificate generated by certgen.
-- ---------------------------------------------------------------------------

INSERT INTO bank (id, bic, name, country, status, settlement_account, notes, onboarded_at) VALUES
  ('a0a0a0a0-aaaa-4000-8000-000000000001', 'BANKUS33', 'First National Bank',    'US', 'PRODUCTION_ACTIVE', 'USD-NOSTRO-001', 'Primary US correspondent — dev seed',  now() - interval '90 days'),
  ('b0b0b0b0-bbbb-4000-8000-000000000002', 'BANKDEFF', 'Deutsche Exchange Bank', 'DE', 'PRODUCTION_ACTIVE', 'EUR-NOSTRO-001', 'Primary EUR correspondent — dev seed',  now() - interval '60 days'),
  ('c0c0c0c0-cccc-4000-8000-000000000003', 'BANKGB2L', 'London Clearing Bank',   'GB', 'PRODUCTION_ACTIVE', 'GBP-NOSTRO-001', 'Primary GBP correspondent — dev seed',  now() - interval '30 days')
ON CONFLICT (bic) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Sample transactions (transaction_view is a read-projection; in production
-- it is populated by the payment-processing flow, but seeding it directly
-- lets the portal dashboard show meaningful data from day one).
--
-- Amounts are in the minor unit of the payment currency (cents for USD/EUR,
-- pence for GBP).  Spread across the last 7 days to populate dashboard buckets.
-- ---------------------------------------------------------------------------

INSERT INTO transaction_view (
    payment_id, end_to_end_id, uetr,
    source_bic, source_bank_name,
    destination_bic, destination_bank_name,
    amount, currency, status, abort_reason,
    charge_bearer, settlement_date,
    debtor_name, creditor_name,
    created_at, updated_at
) VALUES

-- ---- Day −6 ----------------------------------------------------------------
('d0000001-0000-4000-8000-000000000001', 'E2E-D6-001', 'e0000001-0000-4000-8000-000000000001',
 'BANKUS33', 'First National Bank',    'BANKDEFF', 'Deutsche Exchange Bank',
  100000, 'USD', 'SETTLED', NULL, 'SLEV', (now() - interval '6 days')::date,
  'Alice Müller', 'Bob Schmidt', now() - interval '6 days' + interval '08:12:00', now() - interval '6 days' + interval '08:14:22'),

('d0000002-0000-4000-8000-000000000002', 'E2E-D6-002', 'e0000002-0000-4000-8000-000000000002',
 'BANKUS33', 'First National Bank',    'BANKDEFF', 'Deutsche Exchange Bank',
  250000, 'USD', 'SETTLED', NULL, 'SLEV', (now() - interval '6 days')::date,
  'Carol Johnson', 'David Weber', now() - interval '6 days' + interval '11:45:00', now() - interval '6 days' + interval '11:47:03'),

('d0000003-0000-4000-8000-000000000003', 'E2E-D6-003', 'e0000003-0000-4000-8000-000000000003',
 'BANKDEFF', 'Deutsche Exchange Bank', 'BANKGB2L', 'London Clearing Bank',
  180000, 'EUR', 'SETTLED', NULL, 'SLEV', (now() - interval '6 days')::date,
  'Erik Braun',   'Fiona Clarke', now() - interval '6 days' + interval '14:30:00', now() - interval '6 days' + interval '14:32:18'),

-- ---- Day −5 ----------------------------------------------------------------
('d0000004-0000-4000-8000-000000000004', 'E2E-D5-001', 'e0000004-0000-4000-8000-000000000004',
 'BANKUS33', 'First National Bank',    'BANKGB2L', 'London Clearing Bank',
   75000, 'USD', 'SETTLED', NULL, 'SLEV', (now() - interval '5 days')::date,
  'George Adams', 'Hannah Brown', now() - interval '5 days' + interval '09:05:00', now() - interval '5 days' + interval '09:07:11'),

('d0000005-0000-4000-8000-000000000005', 'E2E-D5-002', 'e0000005-0000-4000-8000-000000000005',
 'BANKGB2L', 'London Clearing Bank',   'BANKUS33', 'First National Bank',
  320000, 'GBP', 'SETTLED', NULL, 'SLEV', (now() - interval '5 days')::date,
  'Ivan Shaw',    'Julia White', now() - interval '5 days' + interval '13:20:00', now() - interval '5 days' + interval '13:22:44'),

('d0000006-0000-4000-8000-000000000006', 'E2E-D5-003', 'e0000006-0000-4000-8000-000000000006',
 'BANKDEFF', 'Deutsche Exchange Bank', 'BANKUS33', 'First National Bank',
   90000, 'EUR', 'ABORTED', 'compliance_check_failed', 'SLEV', (now() - interval '5 days')::date,
  'Karl Fischer', 'Laura King',  now() - interval '5 days' + interval '16:00:00', now() - interval '5 days' + interval '16:00:31'),

-- ---- Day −4 ----------------------------------------------------------------
('d0000007-0000-4000-8000-000000000007', 'E2E-D4-001', 'e0000007-0000-4000-8000-000000000007',
 'BANKUS33', 'First National Bank',    'BANKDEFF', 'Deutsche Exchange Bank',
  500000, 'USD', 'SETTLED', NULL, 'SLEV', (now() - interval '4 days')::date,
  'Mike Turner',  'Nina Vogel',  now() - interval '4 days' + interval '07:55:00', now() - interval '4 days' + interval '07:57:39'),

('d0000008-0000-4000-8000-000000000008', 'E2E-D4-002', 'e0000008-0000-4000-8000-000000000008',
 'BANKGB2L', 'London Clearing Bank',   'BANKDEFF', 'Deutsche Exchange Bank',
  200000, 'GBP', 'SETTLED', NULL, 'SLEV', (now() - interval '4 days')::date,
  'Oscar Hill',   'Paula Meyer', now() - interval '4 days' + interval '10:40:00', now() - interval '4 days' + interval '10:42:55'),

('d0000009-0000-4000-8000-000000000009', 'E2E-D4-003', 'e0000009-0000-4000-8000-000000000009',
 'BANKUS33', 'First National Bank',    'BANKGB2L', 'London Clearing Bank',
 1000000, 'USD', 'ABORTED', 'route_not_found', 'SLEV', (now() - interval '4 days')::date,
  'Quinn Ross',   'Rachel Stone', now() - interval '4 days' + interval '15:10:00', now() - interval '4 days' + interval '15:10:09'),

-- ---- Day −3 ----------------------------------------------------------------
('d000000a-0000-4000-8000-00000000000a', 'E2E-D3-001', 'e000000a-0000-4000-8000-00000000000a',
 'BANKDEFF', 'Deutsche Exchange Bank', 'BANKGB2L', 'London Clearing Bank',
  450000, 'EUR', 'SETTLED', NULL, 'SLEV', (now() - interval '3 days')::date,
  'Sam Parker',   'Tina Wright', now() - interval '3 days' + interval '08:30:00', now() - interval '3 days' + interval '08:32:08'),

('d000000b-0000-4000-8000-00000000000b', 'E2E-D3-002', 'e000000b-0000-4000-8000-00000000000b',
 'BANKGB2L', 'London Clearing Bank',   'BANKUS33', 'First National Bank',
  150000, 'GBP', 'SETTLED', NULL, 'SLEV', (now() - interval '3 days')::date,
  'Uma Clark',    'Victor Lane', now() - interval '3 days' + interval '11:15:00', now() - interval '3 days' + interval '11:17:22'),

('d000000c-0000-4000-8000-00000000000c', 'E2E-D3-003', 'e000000c-0000-4000-8000-00000000000c',
 'BANKUS33', 'First National Bank',    'BANKDEFF', 'Deutsche Exchange Bank',
  350000, 'USD', 'SETTLED', NULL, 'DEBT', (now() - interval '3 days')::date,
  'Wendy Fox',    'Xavier Bauer', now() - interval '3 days' + interval '14:00:00', now() - interval '3 days' + interval '14:02:41'),

-- ---- Day −2 ----------------------------------------------------------------
('d000000d-0000-4000-8000-00000000000d', 'E2E-D2-001', 'e000000d-0000-4000-8000-00000000000d',
 'BANKDEFF', 'Deutsche Exchange Bank', 'BANKUS33', 'First National Bank',
  125000, 'EUR', 'COMMITTED', NULL, 'SLEV', (now() - interval '2 days')::date,
  'Yara Green',   'Zach Hall',   now() - interval '2 days' + interval '09:00:00', now() - interval '2 days' + interval '09:02:14'),

('d000000e-0000-4000-8000-00000000000e', 'E2E-D2-002', 'e000000e-0000-4000-8000-00000000000e',
 'BANKGB2L', 'London Clearing Bank',   'BANKUS33', 'First National Bank',
   80000, 'GBP', 'SETTLED', NULL, 'SLEV', (now() - interval '2 days')::date,
  'Anna Bell',    'Brian Cole',  now() - interval '2 days' + interval '13:30:00', now() - interval '2 days' + interval '13:32:05'),

('d000000f-0000-4000-8000-00000000000f', 'E2E-D2-003', 'e000000f-0000-4000-8000-00000000000f',
 'BANKUS33', 'First National Bank',    'BANKGB2L', 'London Clearing Bank',
  220000, 'USD', 'ABORTED', 'insufficient_funds', 'SLEV', (now() - interval '2 days')::date,
  'Chris Dean',   'Diana Evans', now() - interval '2 days' + interval '16:45:00', now() - interval '2 days' + interval '16:45:17'),

-- ---- Day −1 ----------------------------------------------------------------
('d0000010-0000-4000-8000-000000000010', 'E2E-D1-001', 'e0000010-0000-4000-8000-000000000010',
 'BANKDEFF', 'Deutsche Exchange Bank', 'BANKGB2L', 'London Clearing Bank',
  175000, 'EUR', 'SETTLED', NULL, 'SLEV', (now() - interval '1 day')::date,
  'Edward Ford',  'Frances Gray', now() - interval '1 day' + interval '08:20:00', now() - interval '1 day' + interval '08:22:33'),

('d0000011-0000-4000-8000-000000000011', 'E2E-D1-002', 'e0000011-0000-4000-8000-000000000011',
 'BANKGB2L', 'London Clearing Bank',   'BANKDEFF', 'Deutsche Exchange Bank',
  400000, 'GBP', 'SETTLED', NULL, 'SLEV', (now() - interval '1 day')::date,
  'Grace Hunt',   'Henry Ibsen', now() - interval '1 day' + interval '12:00:00', now() - interval '1 day' + interval '12:02:47'),

-- ---- Today -----------------------------------------------------------------
('d0000012-0000-4000-8000-000000000012', 'E2E-D0-001', 'e0000012-0000-4000-8000-000000000012',
 'BANKUS33', 'First National Bank',    'BANKDEFF', 'Deutsche Exchange Bank',
  600000, 'USD', 'SETTLED', NULL, 'SLEV', now()::date,
  'Iris James',   'Jack Klein',  now() - interval '2 hours', now() - interval '2 hours' + interval '00:02:10'),

('d0000013-0000-4000-8000-000000000013', 'E2E-D0-002', 'e0000013-0000-4000-8000-000000000013',
 'BANKDEFF', 'Deutsche Exchange Bank', 'BANKUS33', 'First National Bank',
  290000, 'EUR', 'SETTLED', NULL, 'SLEV', now()::date,
  'Karen Lee',    'Liam Moore',  now() - interval '1 hour', now() - interval '1 hour' + interval '00:01:58'),

('d0000014-0000-4000-8000-000000000014', 'E2E-D0-003', 'e0000014-0000-4000-8000-000000000014',
 'BANKGB2L', 'London Clearing Bank',   'BANKUS33', 'First National Bank',
  150000, 'GBP', 'COMMITTED', NULL, 'SLEV', now()::date,
  'Mia Nash',     'Noah Owen',   now() - interval '30 minutes', now() - interval '30 minutes' + interval '00:01:44')

ON CONFLICT (payment_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Transaction events (timeline for each transaction)
-- We seed 3 events per SETTLED/COMMITTED transaction, 2 for ABORTED.
-- ---------------------------------------------------------------------------

INSERT INTO transaction_event_view (payment_id, event_type, detail, occurred_at) VALUES

-- SETTLED transactions get: received → validated → settled
('d0000001-0000-4000-8000-000000000001', 'payment.received',  '{"step":"validate"}',   now() - interval '6 days' + interval '08:12:00'),
('d0000001-0000-4000-8000-000000000001', 'payment.validated', '{"step":"screen"}',     now() - interval '6 days' + interval '08:12:11'),
('d0000001-0000-4000-8000-000000000001', 'payment.settled',   '{"step":"settle","window":"DAY-6"}', now() - interval '6 days' + interval '08:14:22'),

('d0000002-0000-4000-8000-000000000002', 'payment.received',  '{"step":"validate"}',   now() - interval '6 days' + interval '11:45:00'),
('d0000002-0000-4000-8000-000000000002', 'payment.validated', '{"step":"screen"}',     now() - interval '6 days' + interval '11:45:12'),
('d0000002-0000-4000-8000-000000000002', 'payment.settled',   '{"step":"settle","window":"DAY-6"}', now() - interval '6 days' + interval '11:47:03'),

('d0000003-0000-4000-8000-000000000003', 'payment.received',  '{"step":"validate"}',   now() - interval '6 days' + interval '14:30:00'),
('d0000003-0000-4000-8000-000000000003', 'payment.validated', '{"step":"screen"}',     now() - interval '6 days' + interval '14:30:09'),
('d0000003-0000-4000-8000-000000000003', 'payment.settled',   '{"step":"settle","window":"DAY-6"}', now() - interval '6 days' + interval '14:32:18'),

('d0000004-0000-4000-8000-000000000004', 'payment.received',  '{"step":"validate"}',   now() - interval '5 days' + interval '09:05:00'),
('d0000004-0000-4000-8000-000000000004', 'payment.validated', '{"step":"screen"}',     now() - interval '5 days' + interval '09:05:08'),
('d0000004-0000-4000-8000-000000000004', 'payment.settled',   '{"step":"settle","window":"DAY-5"}', now() - interval '5 days' + interval '09:07:11'),

('d0000005-0000-4000-8000-000000000005', 'payment.received',  '{"step":"validate"}',   now() - interval '5 days' + interval '13:20:00'),
('d0000005-0000-4000-8000-000000000005', 'payment.validated', '{"step":"screen"}',     now() - interval '5 days' + interval '13:20:10'),
('d0000005-0000-4000-8000-000000000005', 'payment.settled',   '{"step":"settle","window":"DAY-5"}', now() - interval '5 days' + interval '13:22:44'),

-- ABORTED transactions get: received → aborted
('d0000006-0000-4000-8000-000000000006', 'payment.received',  '{"step":"validate"}',   now() - interval '5 days' + interval '16:00:00'),
('d0000006-0000-4000-8000-000000000006', 'payment.aborted',   '{"reason":"compliance_check_failed"}', now() - interval '5 days' + interval '16:00:31'),

('d0000007-0000-4000-8000-000000000007', 'payment.received',  '{"step":"validate"}',   now() - interval '4 days' + interval '07:55:00'),
('d0000007-0000-4000-8000-000000000007', 'payment.validated', '{"step":"screen"}',     now() - interval '4 days' + interval '07:55:11'),
('d0000007-0000-4000-8000-000000000007', 'payment.settled',   '{"step":"settle","window":"DAY-4"}', now() - interval '4 days' + interval '07:57:39'),

('d0000008-0000-4000-8000-000000000008', 'payment.received',  '{"step":"validate"}',   now() - interval '4 days' + interval '10:40:00'),
('d0000008-0000-4000-8000-000000000008', 'payment.validated', '{"step":"screen"}',     now() - interval '4 days' + interval '10:40:09'),
('d0000008-0000-4000-8000-000000000008', 'payment.settled',   '{"step":"settle","window":"DAY-4"}', now() - interval '4 days' + interval '10:42:55'),

('d0000009-0000-4000-8000-000000000009', 'payment.received',  '{"step":"validate"}',   now() - interval '4 days' + interval '15:10:00'),
('d0000009-0000-4000-8000-000000000009', 'payment.aborted',   '{"reason":"route_not_found"}', now() - interval '4 days' + interval '15:10:09'),

('d000000a-0000-4000-8000-00000000000a', 'payment.received',  '{"step":"validate"}',   now() - interval '3 days' + interval '08:30:00'),
('d000000a-0000-4000-8000-00000000000a', 'payment.validated', '{"step":"screen"}',     now() - interval '3 days' + interval '08:30:08'),
('d000000a-0000-4000-8000-00000000000a', 'payment.settled',   '{"step":"settle","window":"DAY-3"}', now() - interval '3 days' + interval '08:32:08'),

('d000000b-0000-4000-8000-00000000000b', 'payment.received',  '{"step":"validate"}',   now() - interval '3 days' + interval '11:15:00'),
('d000000b-0000-4000-8000-00000000000b', 'payment.validated', '{"step":"screen"}',     now() - interval '3 days' + interval '11:15:10'),
('d000000b-0000-4000-8000-00000000000b', 'payment.settled',   '{"step":"settle","window":"DAY-3"}', now() - interval '3 days' + interval '11:17:22'),

('d000000c-0000-4000-8000-00000000000c', 'payment.received',  '{"step":"validate"}',   now() - interval '3 days' + interval '14:00:00'),
('d000000c-0000-4000-8000-00000000000c', 'payment.validated', '{"step":"screen"}',     now() - interval '3 days' + interval '14:00:12'),
('d000000c-0000-4000-8000-00000000000c', 'payment.settled',   '{"step":"settle","window":"DAY-3"}', now() - interval '3 days' + interval '14:02:41'),

('d000000d-0000-4000-8000-00000000000d', 'payment.received',  '{"step":"validate"}',   now() - interval '2 days' + interval '09:00:00'),
('d000000d-0000-4000-8000-00000000000d', 'payment.validated', '{"step":"screen"}',     now() - interval '2 days' + interval '09:00:11'),
('d000000d-0000-4000-8000-00000000000d', 'payment.committed', '{"step":"commit"}',     now() - interval '2 days' + interval '09:02:14'),

('d000000e-0000-4000-8000-00000000000e', 'payment.received',  '{"step":"validate"}',   now() - interval '2 days' + interval '13:30:00'),
('d000000e-0000-4000-8000-00000000000e', 'payment.validated', '{"step":"screen"}',     now() - interval '2 days' + interval '13:30:09'),
('d000000e-0000-4000-8000-00000000000e', 'payment.settled',   '{"step":"settle","window":"DAY-2"}', now() - interval '2 days' + interval '13:32:05'),

('d000000f-0000-4000-8000-00000000000f', 'payment.received',  '{"step":"validate"}',   now() - interval '2 days' + interval '16:45:00'),
('d000000f-0000-4000-8000-00000000000f', 'payment.aborted',   '{"reason":"insufficient_funds"}', now() - interval '2 days' + interval '16:45:17'),

('d0000010-0000-4000-8000-000000000010', 'payment.received',  '{"step":"validate"}',   now() - interval '1 day' + interval '08:20:00'),
('d0000010-0000-4000-8000-000000000010', 'payment.validated', '{"step":"screen"}',     now() - interval '1 day' + interval '08:20:10'),
('d0000010-0000-4000-8000-000000000010', 'payment.settled',   '{"step":"settle","window":"DAY-1"}', now() - interval '1 day' + interval '08:22:33'),

('d0000011-0000-4000-8000-000000000011', 'payment.received',  '{"step":"validate"}',   now() - interval '1 day' + interval '12:00:00'),
('d0000011-0000-4000-8000-000000000011', 'payment.validated', '{"step":"screen"}',     now() - interval '1 day' + interval '12:00:08'),
('d0000011-0000-4000-8000-000000000011', 'payment.settled',   '{"step":"settle","window":"DAY-1"}', now() - interval '1 day' + interval '12:02:47'),

('d0000012-0000-4000-8000-000000000012', 'payment.received',  '{"step":"validate"}',   now() - interval '2 hours'),
('d0000012-0000-4000-8000-000000000012', 'payment.validated', '{"step":"screen"}',     now() - interval '2 hours' + interval '00:00:11'),
('d0000012-0000-4000-8000-000000000012', 'payment.settled',   '{"step":"settle","window":"TODAY"}', now() - interval '2 hours' + interval '00:02:10'),

('d0000013-0000-4000-8000-000000000013', 'payment.received',  '{"step":"validate"}',   now() - interval '1 hour'),
('d0000013-0000-4000-8000-000000000013', 'payment.validated', '{"step":"screen"}',     now() - interval '1 hour' + interval '00:00:09'),
('d0000013-0000-4000-8000-000000000013', 'payment.settled',   '{"step":"settle","window":"TODAY"}', now() - interval '1 hour' + interval '00:01:58'),

('d0000014-0000-4000-8000-000000000014', 'payment.received',  '{"step":"validate"}',   now() - interval '30 minutes'),
('d0000014-0000-4000-8000-000000000014', 'payment.validated', '{"step":"screen"}',     now() - interval '30 minutes' + interval '00:00:10'),
('d0000014-0000-4000-8000-000000000014', 'payment.committed', '{"step":"commit"}',     now() - interval '30 minutes' + interval '00:01:44')

ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Audit log — seed bank onboarding events
-- ---------------------------------------------------------------------------

INSERT INTO audit_log (actor_id, actor_role, action, target_type, target_id, diff) VALUES
  ('system', 'SWITCH_ADMIN', 'bank.create', 'bank', 'a0a0a0a0-aaaa-4000-8000-000000000001', '{"bic":"BANKUS33","name":"First National Bank"}'),
  ('system', 'SWITCH_ADMIN', 'bank.create', 'bank', 'b0b0b0b0-bbbb-4000-8000-000000000002', '{"bic":"BANKDEFF","name":"Deutsche Exchange Bank"}'),
  ('system', 'SWITCH_ADMIN', 'bank.create', 'bank', 'c0c0c0c0-cccc-4000-8000-000000000003', '{"bic":"BANKGB2L","name":"London Clearing Bank"}'),
  ('system', 'SWITCH_ADMIN', 'bank.status_change', 'bank', 'a0a0a0a0-aaaa-4000-8000-000000000001', '{"from":"APPLICATION","to":"PRODUCTION_ACTIVE"}'),
  ('system', 'SWITCH_ADMIN', 'bank.status_change', 'bank', 'b0b0b0b0-bbbb-4000-8000-000000000002', '{"from":"APPLICATION","to":"PRODUCTION_ACTIVE"}'),
  ('system', 'SWITCH_ADMIN', 'bank.status_change', 'bank', 'c0c0c0c0-cccc-4000-8000-000000000003', '{"from":"APPLICATION","to":"PRODUCTION_ACTIVE"}');
