global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'payment-switch'
    static_configs:
      - targets:
          - 'gateway:9095'
          - 'compliance-service:9095'
          - 'lookup-service:9095'
          - 'settlement-service:9095'
          - 'quoting-service:9095'
          - 'notification-service:9095'
          - 'routing-service:9095'
          - 'reconciliation-service:9095'
          - 'portal-api:9095'
