// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: reconciliation.proto

package reconciliationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	SourceBic     string                 `protobuf:"bytes,2,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestBic       string                 `protobuf:"bytes,3,opt,name=dest_bic,json=destBic,proto3" json:"dest_bic,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Matched       bool                   `protobuf:"varint,7,opt,name=matched,proto3" json:"matched,omitempty"`
	Discrepancy   string                 `protobuf:"bytes,8,opt,name=discrepancy,proto3" json:"discrepancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_reconciliation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Record) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *Record) GetDestBic() string {
	if x != nil {
		return x.DestBic
	}
	return ""
}

func (x *Record) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Record) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Record) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Record) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *Record) GetDiscrepancy() string {
	if x != nil {
		return x.Discrepancy
	}
	return ""
}

type AddRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordRequest) Reset() {
	*x = AddRecordRequest{}
	mi := &file_reconciliation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordRequest) ProtoMessage() {}

func (x *AddRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordRequest.ProtoReflect.Descriptor instead.
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{1}
}

func (x *AddRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type AddRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordResponse) Reset() {
	*x = AddRecordResponse{}
	mi := &file_reconciliation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordResponse) ProtoMessage() {}

func (x *AddRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordResponse.ProtoReflect.Descriptor instead.
func (*AddRecordResponse) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{2}
}

type MatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentId      string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ExpectedStatus string                 `protobuf:"bytes,2,opt,name=expected_status,json=expectedStatus,proto3" json:"expected_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_reconciliation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{3}
}

func (x *MatchRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MatchRequest) GetExpectedStatus() string {
	if x != nil {
		return x.ExpectedStatus
	}
	return ""
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_reconciliation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{4}
}

func (x *MatchResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_reconciliation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{5}
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_reconciliation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{6}
}

func (x *ReportResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type ImportExternalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportExternalRequest) Reset() {
	*x = ImportExternalRequest{}
	mi := &file_reconciliation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportExternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportExternalRequest) ProtoMessage() {}

func (x *ImportExternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportExternalRequest.ProtoReflect.Descriptor instead.
func (*ImportExternalRequest) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{7}
}

func (x *ImportExternalRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ImportExternalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportExternalResponse) Reset() {
	*x = ImportExternalResponse{}
	mi := &file_reconciliation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportExternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportExternalResponse) ProtoMessage() {}

func (x *ImportExternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconciliation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportExternalResponse.ProtoReflect.Descriptor instead.
func (*ImportExternalResponse) Descriptor() ([]byte, []int) {
	return file_reconciliation_proto_rawDescGZIP(), []int{8}
}

var File_reconciliation_proto protoreflect.FileDescriptor

const file_reconciliation_proto_rawDesc = "" +
	"\n" +
	"\x14reconciliation.proto\x12\tswitch.v1\"\xe9\x01\n" +
	"\x06Record\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x02 \x01(\tR\tsourceBic\x12\x19\n" +
	"\bdest_bic\x18\x03 \x01(\tR\adestBic\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\amatched\x18\a \x01(\bR\amatched\x12 \n" +
	"\vdiscrepancy\x18\b \x01(\tR\vdiscrepancy\"=\n" +
	"\x10AddRecordRequest\x12)\n" +
	"\x06record\x18\x01 \x01(\v2\x11.switch.v1.RecordR\x06record\"\x13\n" +
	"\x11AddRecordResponse\"V\n" +
	"\fMatchRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12'\n" +
	"\x0fexpected_status\x18\x02 \x01(\tR\x0eexpectedStatus\"5\n" +
	"\rMatchResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rReportRequest\"=\n" +
	"\x0eReportResponse\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.switch.v1.RecordR\arecords\"/\n" +
	"\x15ImportExternalRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"\x18\n" +
	"\x16ImportExternalResponse2\xaa\x02\n" +
	"\x0eReconciliation\x12F\n" +
	"\tAddRecord\x12\x1b.switch.v1.AddRecordRequest\x1a\x1c.switch.v1.AddRecordResponse\x12:\n" +
	"\x05Match\x12\x17.switch.v1.MatchRequest\x1a\x18.switch.v1.MatchResponse\x12=\n" +
	"\x06Report\x12\x18.switch.v1.ReportRequest\x1a\x19.switch.v1.ReportResponse\x12U\n" +
	"\x0eImportExternal\x12 .switch.v1.ImportExternalRequest\x1a!.switch.v1.ImportExternalResponseB2Z0switch/api/proto/reconciliation;reconciliationpbb\x06proto3"

var (
	file_reconciliation_proto_rawDescOnce sync.Once
	file_reconciliation_proto_rawDescData []byte
)

func file_reconciliation_proto_rawDescGZIP() []byte {
	file_reconciliation_proto_rawDescOnce.Do(func() {
		file_reconciliation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reconciliation_proto_rawDesc), len(file_reconciliation_proto_rawDesc)))
	})
	return file_reconciliation_proto_rawDescData
}

var file_reconciliation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_reconciliation_proto_goTypes = []any{
	(*Record)(nil),                 // 0: switch.v1.Record
	(*AddRecordRequest)(nil),       // 1: switch.v1.AddRecordRequest
	(*AddRecordResponse)(nil),      // 2: switch.v1.AddRecordResponse
	(*MatchRequest)(nil),           // 3: switch.v1.MatchRequest
	(*MatchResponse)(nil),          // 4: switch.v1.MatchResponse
	(*ReportRequest)(nil),          // 5: switch.v1.ReportRequest
	(*ReportResponse)(nil),         // 6: switch.v1.ReportResponse
	(*ImportExternalRequest)(nil),  // 7: switch.v1.ImportExternalRequest
	(*ImportExternalResponse)(nil), // 8: switch.v1.ImportExternalResponse
}
var file_reconciliation_proto_depIdxs = []int32{
	0, // 0: switch.v1.AddRecordRequest.record:type_name -> switch.v1.Record
	0, // 1: switch.v1.ReportResponse.records:type_name -> switch.v1.Record
	1, // 2: switch.v1.Reconciliation.AddRecord:input_type -> switch.v1.AddRecordRequest
	3, // 3: switch.v1.Reconciliation.Match:input_type -> switch.v1.MatchRequest
	5, // 4: switch.v1.Reconciliation.Report:input_type -> switch.v1.ReportRequest
	7, // 5: switch.v1.Reconciliation.ImportExternal:input_type -> switch.v1.ImportExternalRequest
	2, // 6: switch.v1.Reconciliation.AddRecord:output_type -> switch.v1.AddRecordResponse
	4, // 7: switch.v1.Reconciliation.Match:output_type -> switch.v1.MatchResponse
	6, // 8: switch.v1.Reconciliation.Report:output_type -> switch.v1.ReportResponse
	8, // 9: switch.v1.Reconciliation.ImportExternal:output_type -> switch.v1.ImportExternalResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reconciliation_proto_init() }
func file_reconciliation_proto_init() {
	if File_reconciliation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reconciliation_proto_rawDesc), len(file_reconciliation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reconciliation_proto_goTypes,
		DependencyIndexes: file_reconciliation_proto_depIdxs,
		MessageInfos:      file_reconciliation_proto_msgTypes,
	}.Build()
	File_reconciliation_proto = out.File
	file_reconciliation_proto_goTypes = nil
	file_reconciliation_proto_depIdxs = nil
}
