// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: reconciliation.proto

package reconciliationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reconciliation_AddRecord_FullMethodName      = "/switch.v1.Reconciliation/AddRecord"
	Reconciliation_Match_FullMethodName          = "/switch.v1.Reconciliation/Match"
	Reconciliation_Report_FullMethodName         = "/switch.v1.Reconciliation/Report"
	Reconciliation_ImportExternal_FullMethodName = "/switch.v1.Reconciliation/ImportExternal"
)

// ReconciliationClient is the client API for Reconciliation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReconciliationClient interface {
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	ImportExternal(ctx context.Context, in *ImportExternalRequest, opts ...grpc.CallOption) (*ImportExternalResponse, error)
}

type reconciliationClient struct {
	cc grpc.ClientConnInterface
}

func NewReconciliationClient(cc grpc.ClientConnInterface) ReconciliationClient {
	return &reconciliationClient{cc}
}

func (c *reconciliationClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, Reconciliation_AddRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, Reconciliation_Match_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, Reconciliation_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconciliationClient) ImportExternal(ctx context.Context, in *ImportExternalRequest, opts ...grpc.CallOption) (*ImportExternalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportExternalResponse)
	err := c.cc.Invoke(ctx, Reconciliation_ImportExternal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReconciliationServer is the server API for Reconciliation service.
// All implementations must embed UnimplementedReconciliationServer
// for forward compatibility.
type ReconciliationServer interface {
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	ImportExternal(context.Context, *ImportExternalRequest) (*ImportExternalResponse, error)
	mustEmbedUnimplementedReconciliationServer()
}

// UnimplementedReconciliationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReconciliationServer struct{}

func (UnimplementedReconciliationServer) AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedReconciliationServer) Match(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Match not implemented")
}
func (UnimplementedReconciliationServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedReconciliationServer) ImportExternal(context.Context, *ImportExternalRequest) (*ImportExternalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportExternal not implemented")
}
func (UnimplementedReconciliationServer) mustEmbedUnimplementedReconciliationServer() {}
func (UnimplementedReconciliationServer) testEmbeddedByValue()                        {}

// UnsafeReconciliationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReconciliationServer will
// result in compilation errors.
type UnsafeReconciliationServer interface {
	mustEmbedUnimplementedReconciliationServer()
}

func RegisterReconciliationServer(s grpc.ServiceRegistrar, srv ReconciliationServer) {
	// If the following call panics, it indicates UnimplementedReconciliationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reconciliation_ServiceDesc, srv)
}

func _Reconciliation_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reconciliation_AddRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reconciliation_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reconciliation_Match_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reconciliation_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reconciliation_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reconciliation_ImportExternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportExternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconciliationServer).ImportExternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reconciliation_ImportExternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconciliationServer).ImportExternal(ctx, req.(*ImportExternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reconciliation_ServiceDesc is the grpc.ServiceDesc for Reconciliation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reconciliation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Reconciliation",
	HandlerType: (*ReconciliationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _Reconciliation_AddRecord_Handler,
		},
		{
			MethodName: "Match",
			Handler:    _Reconciliation_Match_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _Reconciliation_Report_Handler,
		},
		{
			MethodName: "ImportExternal",
			Handler:    _Reconciliation_ImportExternal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reconciliation.proto",
}
