// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: quoting.proto

package quotingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Quoting_GetQuote_FullMethodName    = "/switch.v1.Quoting/GetQuote"
	Quoting_AcceptQuote_FullMethodName = "/switch.v1.Quoting/AcceptQuote"
)

// QuotingClient is the client API for Quoting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuotingClient interface {
	GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	AcceptQuote(ctx context.Context, in *AcceptQuoteRequest, opts ...grpc.CallOption) (*AcceptQuoteResponse, error)
}

type quotingClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotingClient(cc grpc.ClientConnInterface) QuotingClient {
	return &quotingClient{cc}
}

func (c *quotingClient) GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, Quoting_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotingClient) AcceptQuote(ctx context.Context, in *AcceptQuoteRequest, opts ...grpc.CallOption) (*AcceptQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptQuoteResponse)
	err := c.cc.Invoke(ctx, Quoting_AcceptQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotingServer is the server API for Quoting service.
// All implementations must embed UnimplementedQuotingServer
// for forward compatibility.
type QuotingServer interface {
	GetQuote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	AcceptQuote(context.Context, *AcceptQuoteRequest) (*AcceptQuoteResponse, error)
	mustEmbedUnimplementedQuotingServer()
}

// UnimplementedQuotingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuotingServer struct{}

func (UnimplementedQuotingServer) GetQuote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedQuotingServer) AcceptQuote(context.Context, *AcceptQuoteRequest) (*AcceptQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptQuote not implemented")
}
func (UnimplementedQuotingServer) mustEmbedUnimplementedQuotingServer() {}
func (UnimplementedQuotingServer) testEmbeddedByValue()                 {}

// UnsafeQuotingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotingServer will
// result in compilation errors.
type UnsafeQuotingServer interface {
	mustEmbedUnimplementedQuotingServer()
}

func RegisterQuotingServer(s grpc.ServiceRegistrar, srv QuotingServer) {
	// If the following call panics, it indicates UnimplementedQuotingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Quoting_ServiceDesc, srv)
}

func _Quoting_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotingServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Quoting_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotingServer).GetQuote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Quoting_AcceptQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotingServer).AcceptQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Quoting_AcceptQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotingServer).AcceptQuote(ctx, req.(*AcceptQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Quoting_ServiceDesc is the grpc.ServiceDesc for Quoting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Quoting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Quoting",
	HandlerType: (*QuotingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _Quoting_GetQuote_Handler,
		},
		{
			MethodName: "AcceptQuote",
			Handler:    _Quoting_AcceptQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quoting.proto",
}
