// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: quoting.proto

package quotingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceBic      string                 `protobuf:"bytes,1,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestinationBic string                 `protobuf:"bytes,2,opt,name=destination_bic,json=destinationBic,proto3" json:"destination_bic,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_quoting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quoting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_quoting_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *QuoteRequest) GetDestinationBic() string {
	if x != nil {
		return x.DestinationBic
	}
	return ""
}

func (x *QuoteRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QuoteRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Quote struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceBic          string                 `protobuf:"bytes,2,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestinationBic     string                 `protobuf:"bytes,3,opt,name=destination_bic,json=destinationBic,proto3" json:"destination_bic,omitempty"`
	Amount             int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Fee                int64                  `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Total              int64                  `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	EstimatedLatencyMs int64                  `protobuf:"varint,8,opt,name=estimated_latency_ms,json=estimatedLatencyMs,proto3" json:"estimated_latency_ms,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Accepted           bool                   `protobuf:"varint,10,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_quoting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_quoting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_quoting_proto_rawDescGZIP(), []int{1}
}

func (x *Quote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quote) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *Quote) GetDestinationBic() string {
	if x != nil {
		return x.DestinationBic
	}
	return ""
}

func (x *Quote) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Quote) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Quote) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Quote) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Quote) GetEstimatedLatencyMs() int64 {
	if x != nil {
		return x.EstimatedLatencyMs
	}
	return 0
}

func (x *Quote) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Quote) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         *Quote                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_quoting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quoting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_quoting_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteResponse) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

type AcceptQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptQuoteRequest) Reset() {
	*x = AcceptQuoteRequest{}
	mi := &file_quoting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuoteRequest) ProtoMessage() {}

func (x *AcceptQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quoting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuoteRequest.ProtoReflect.Descriptor instead.
func (*AcceptQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quoting_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type AcceptQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptQuoteResponse) Reset() {
	*x = AcceptQuoteResponse{}
	mi := &file_quoting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuoteResponse) ProtoMessage() {}

func (x *AcceptQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quoting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuoteResponse.ProtoReflect.Descriptor instead.
func (*AcceptQuoteResponse) Descriptor() ([]byte, []int) {
	return file_quoting_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptQuoteResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_quoting_proto protoreflect.FileDescriptor

const file_quoting_proto_rawDesc = "" +
	"\n" +
	"\rquoting.proto\x12\tswitch.v1\"\x8a\x01\n" +
	"\fQuoteRequest\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x01 \x01(\tR\tsourceBic\x12'\n" +
	"\x0fdestination_bic\x18\x02 \x01(\tR\x0edestinationBic\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xa8\x02\n" +
	"\x05Quote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x02 \x01(\tR\tsourceBic\x12'\n" +
	"\x0fdestination_bic\x18\x03 \x01(\tR\x0edestinationBic\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x03R\x03fee\x12\x14\n" +
	"\x05total\x18\a \x01(\x03R\x05total\x120\n" +
	"\x14estimated_latency_ms\x18\b \x01(\x03R\x12estimatedLatencyMs\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\x12\x1a\n" +
	"\baccepted\x18\n" +
	" \x01(\bR\baccepted\"7\n" +
	"\rQuoteResponse\x12&\n" +
	"\x05quote\x18\x01 \x01(\v2\x10.switch.v1.QuoteR\x05quote\"/\n" +
	"\x12AcceptQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\"1\n" +
	"\x13AcceptQuoteResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\x96\x01\n" +
	"\aQuoting\x12=\n" +
	"\bGetQuote\x12\x17.switch.v1.QuoteRequest\x1a\x18.switch.v1.QuoteResponse\x12L\n" +
	"\vAcceptQuote\x12\x1d.switch.v1.AcceptQuoteRequest\x1a\x1e.switch.v1.AcceptQuoteResponseB$Z\"switch/api/proto/quoting;quotingpbb\x06proto3"

var (
	file_quoting_proto_rawDescOnce sync.Once
	file_quoting_proto_rawDescData []byte
)

func file_quoting_proto_rawDescGZIP() []byte {
	file_quoting_proto_rawDescOnce.Do(func() {
		file_quoting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quoting_proto_rawDesc), len(file_quoting_proto_rawDesc)))
	})
	return file_quoting_proto_rawDescData
}

var file_quoting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quoting_proto_goTypes = []any{
	(*QuoteRequest)(nil),        // 0: switch.v1.QuoteRequest
	(*Quote)(nil),               // 1: switch.v1.Quote
	(*QuoteResponse)(nil),       // 2: switch.v1.QuoteResponse
	(*AcceptQuoteRequest)(nil),  // 3: switch.v1.AcceptQuoteRequest
	(*AcceptQuoteResponse)(nil), // 4: switch.v1.AcceptQuoteResponse
}
var file_quoting_proto_depIdxs = []int32{
	1, // 0: switch.v1.QuoteResponse.quote:type_name -> switch.v1.Quote
	0, // 1: switch.v1.Quoting.GetQuote:input_type -> switch.v1.QuoteRequest
	3, // 2: switch.v1.Quoting.AcceptQuote:input_type -> switch.v1.AcceptQuoteRequest
	2, // 3: switch.v1.Quoting.GetQuote:output_type -> switch.v1.QuoteResponse
	4, // 4: switch.v1.Quoting.AcceptQuote:output_type -> switch.v1.AcceptQuoteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quoting_proto_init() }
func file_quoting_proto_init() {
	if File_quoting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quoting_proto_rawDesc), len(file_quoting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quoting_proto_goTypes,
		DependencyIndexes: file_quoting_proto_depIdxs,
		MessageInfos:      file_quoting_proto_msgTypes,
	}.Build()
	File_quoting_proto = out.File
	file_quoting_proto_goTypes = nil
	file_quoting_proto_depIdxs = nil
}
