// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID             string
	EndToEndID     string
	SourceBic      string
	DestinationBic string
	SourceAccount  string
	DestAccount    string
	Amount         int64
	Currency       string
	Status         string
	QuoteID        pgtype.Text
	ReservedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	// ISO 20022 fields (added by migration 0002)
	UETR           pgtype.Text
	InstrID        pgtype.Text
	ChargeBearer   pgtype.Text
	SttlmDt        pgtype.Date
	DebtorName     pgtype.Text
	CreditorName   pgtype.Text
	PurposeCode    pgtype.Text
	RemittanceInfo pgtype.Text
}
