// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (id, end_to_end_id, source_bic, destination_bic,
                     source_account, dest_account, amount, currency, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, end_to_end_id, source_bic, destination_bic, source_account, dest_account, amount, currency, status, quote_id, reserved_at, expires_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ID             string
	EndToEndID     string
	SourceBic      string
	DestinationBic string
	SourceAccount  string
	DestAccount    string
	Amount         int64
	Currency       string
	Status         string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (*Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.EndToEndID,
		arg.SourceBic,
		arg.DestinationBic,
		arg.SourceAccount,
		arg.DestAccount,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.EndToEndID,
		&i.SourceBic,
		&i.DestinationBic,
		&i.SourceAccount,
		&i.DestAccount,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.QuoteID,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findExpiredReservations = `-- name: FindExpiredReservations :many
SELECT id, source_account, amount, reserved_at, expires_at
FROM payment
WHERE status = 'RESERVED' AND expires_at < $1
FOR UPDATE SKIP LOCKED
`

type FindExpiredReservationsRow struct {
	ID            string
	SourceAccount string
	Amount        int64
	ReservedAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) FindExpiredReservations(ctx context.Context, expiresAt pgtype.Timestamptz) ([]*FindExpiredReservationsRow, error) {
	rows, err := q.db.Query(ctx, findExpiredReservations, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*FindExpiredReservationsRow
	for rows.Next() {
		var i FindExpiredReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceAccount,
			&i.Amount,
			&i.ReservedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByEndToEndID = `-- name: GetPaymentByEndToEndID :one
SELECT id, end_to_end_id, source_bic, destination_bic, source_account, dest_account, amount, currency, status, quote_id, reserved_at, expires_at, created_at, updated_at FROM payment WHERE end_to_end_id = $1
`

func (q *Queries) GetPaymentByEndToEndID(ctx context.Context, endToEndID string) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByEndToEndID, endToEndID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.EndToEndID,
		&i.SourceBic,
		&i.DestinationBic,
		&i.SourceAccount,
		&i.DestAccount,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.QuoteID,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, end_to_end_id, source_bic, destination_bic, source_account, dest_account, amount, currency, status, quote_id, reserved_at, expires_at, created_at, updated_at FROM payment WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.EndToEndID,
		&i.SourceBic,
		&i.DestinationBic,
		&i.SourceAccount,
		&i.DestAccount,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.QuoteID,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentEventFields = `-- name: GetPaymentEventFields :one
SELECT id, end_to_end_id, source_bic, destination_bic, amount, currency
FROM payment WHERE id = $1
`

type GetPaymentEventFieldsRow struct {
	ID             string
	EndToEndID     string
	SourceBic      string
	DestinationBic string
	Amount         int64
	Currency       string
}

func (q *Queries) GetPaymentEventFields(ctx context.Context, id string) (*GetPaymentEventFieldsRow, error) {
	row := q.db.QueryRow(ctx, getPaymentEventFields, id)
	var i GetPaymentEventFieldsRow
	err := row.Scan(
		&i.ID,
		&i.EndToEndID,
		&i.SourceBic,
		&i.DestinationBic,
		&i.Amount,
		&i.Currency,
	)
	return &i, err
}

const markPaymentReserved = `-- name: MarkPaymentReserved :exec
UPDATE payment
SET status = $1, reserved_at = $2, expires_at = $3, updated_at = now()
WHERE id = $4
`

type MarkPaymentReservedParams struct {
	Status     string
	ReservedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ID         string
}

func (q *Queries) MarkPaymentReserved(ctx context.Context, arg MarkPaymentReservedParams) error {
	_, err := q.db.Exec(ctx, markPaymentReserved,
		arg.Status,
		arg.ReservedAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payment SET status = $1, updated_at = now() WHERE id = $2
`

type UpdatePaymentStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus, arg.Status, arg.ID)
	return err
}

const updatePaymentStatusReturning = `-- name: UpdatePaymentStatusReturning :one
UPDATE payment SET status = $1, updated_at = now() WHERE id = $2
RETURNING status
`

type UpdatePaymentStatusReturningParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdatePaymentStatusReturning(ctx context.Context, arg UpdatePaymentStatusReturningParams) (string, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatusReturning, arg.Status, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}
