// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (*Payment, error)
	FindExpiredReservations(ctx context.Context, expiresAt pgtype.Timestamptz) ([]*FindExpiredReservationsRow, error)
	GetPaymentByEndToEndID(ctx context.Context, endToEndID string) (*Payment, error)
	GetPaymentByID(ctx context.Context, id string) (*Payment, error)
	GetPaymentEventFields(ctx context.Context, id string) (*GetPaymentEventFieldsRow, error)
	MarkPaymentReserved(ctx context.Context, arg MarkPaymentReservedParams) error
	UpdatePaymentRoute(ctx context.Context, arg UpdatePaymentRouteParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdatePaymentStatusReturning(ctx context.Context, arg UpdatePaymentStatusReturningParams) (string, error)
}

var _ Querier = (*Queries)(nil)
