// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: compliance.proto

package compliancepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	payment "switch/api/proto/payment"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *payment.Payment       `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenRequest) Reset() {
	*x = ScreenRequest{}
	mi := &file_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenRequest) ProtoMessage() {}

func (x *ScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenRequest.ProtoReflect.Descriptor instead.
func (*ScreenRequest) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenRequest) GetPayment() *payment.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *ScreenRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type ScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       bool                   `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenResponse) Reset() {
	*x = ScreenResponse{}
	mi := &file_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenResponse) ProtoMessage() {}

func (x *ScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenResponse.ProtoReflect.Descriptor instead.
func (*ScreenResponse) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenResponse) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

func (x *ScreenResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_compliance_proto protoreflect.FileDescriptor

const file_compliance_proto_rawDesc = "" +
	"\n" +
	"\x10compliance.proto\x12\tswitch.v1\x1a\rpayment.proto\"d\n" +
	"\rScreenRequest\x12,\n" +
	"\apayment\x18\x01 \x01(\v2\x12.switch.v1.PaymentR\apayment\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"B\n" +
	"\x0eScreenResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2K\n" +
	"\n" +
	"Compliance\x12=\n" +
	"\x06Screen\x12\x18.switch.v1.ScreenRequest\x1a\x19.switch.v1.ScreenResponseB*Z(switch/api/proto/compliance;compliancepbb\x06proto3"

var (
	file_compliance_proto_rawDescOnce sync.Once
	file_compliance_proto_rawDescData []byte
)

func file_compliance_proto_rawDescGZIP() []byte {
	file_compliance_proto_rawDescOnce.Do(func() {
		file_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compliance_proto_rawDesc), len(file_compliance_proto_rawDesc)))
	})
	return file_compliance_proto_rawDescData
}

var file_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_compliance_proto_goTypes = []any{
	(*ScreenRequest)(nil),   // 0: switch.v1.ScreenRequest
	(*ScreenResponse)(nil),  // 1: switch.v1.ScreenResponse
	(*payment.Payment)(nil), // 2: switch.v1.Payment
}
var file_compliance_proto_depIdxs = []int32{
	2, // 0: switch.v1.ScreenRequest.payment:type_name -> switch.v1.Payment
	0, // 1: switch.v1.Compliance.Screen:input_type -> switch.v1.ScreenRequest
	1, // 2: switch.v1.Compliance.Screen:output_type -> switch.v1.ScreenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_compliance_proto_init() }
func file_compliance_proto_init() {
	if File_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compliance_proto_rawDesc), len(file_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compliance_proto_goTypes,
		DependencyIndexes: file_compliance_proto_depIdxs,
		MessageInfos:      file_compliance_proto_msgTypes,
	}.Build()
	File_compliance_proto = out.File
	file_compliance_proto_goTypes = nil
	file_compliance_proto_depIdxs = nil
}
