// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: compliance.proto

package compliancepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Compliance_Screen_FullMethodName = "/switch.v1.Compliance/Screen"
)

// ComplianceClient is the client API for Compliance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComplianceClient interface {
	// Screen a payment against sanctions/regulatory lists.
	Screen(ctx context.Context, in *ScreenRequest, opts ...grpc.CallOption) (*ScreenResponse, error)
}

type complianceClient struct {
	cc grpc.ClientConnInterface
}

func NewComplianceClient(cc grpc.ClientConnInterface) ComplianceClient {
	return &complianceClient{cc}
}

func (c *complianceClient) Screen(ctx context.Context, in *ScreenRequest, opts ...grpc.CallOption) (*ScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenResponse)
	err := c.cc.Invoke(ctx, Compliance_Screen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplianceServer is the server API for Compliance service.
// All implementations must embed UnimplementedComplianceServer
// for forward compatibility.
type ComplianceServer interface {
	// Screen a payment against sanctions/regulatory lists.
	Screen(context.Context, *ScreenRequest) (*ScreenResponse, error)
	mustEmbedUnimplementedComplianceServer()
}

// UnimplementedComplianceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplianceServer struct{}

func (UnimplementedComplianceServer) Screen(context.Context, *ScreenRequest) (*ScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screen not implemented")
}
func (UnimplementedComplianceServer) mustEmbedUnimplementedComplianceServer() {}
func (UnimplementedComplianceServer) testEmbeddedByValue()                    {}

// UnsafeComplianceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplianceServer will
// result in compilation errors.
type UnsafeComplianceServer interface {
	mustEmbedUnimplementedComplianceServer()
}

func RegisterComplianceServer(s grpc.ServiceRegistrar, srv ComplianceServer) {
	// If the following call panics, it indicates UnimplementedComplianceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Compliance_ServiceDesc, srv)
}

func _Compliance_Screen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServer).Screen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Compliance_Screen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServer).Screen(ctx, req.(*ScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Compliance_ServiceDesc is the grpc.ServiceDesc for Compliance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compliance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Compliance",
	HandlerType: (*ComplianceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screen",
			Handler:    _Compliance_Screen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compliance.proto",
}
