// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: settlement.proto

package settlementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	payment "switch/api/proto/payment"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettlementAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	WindowId      string                 `protobuf:"bytes,2,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementAck) Reset() {
	*x = SettlementAck{}
	mi := &file_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementAck) ProtoMessage() {}

func (x *SettlementAck) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementAck.ProtoReflect.Descriptor instead.
func (*SettlementAck) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *SettlementAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SettlementAck) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type SettleWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleWindowRequest) Reset() {
	*x = SettleWindowRequest{}
	mi := &file_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleWindowRequest) ProtoMessage() {}

func (x *SettleWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleWindowRequest.ProtoReflect.Descriptor instead.
func (*SettleWindowRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *SettleWindowRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type SettleWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*NetPosition         `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	WindowId      string                 `protobuf:"bytes,2,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleWindowResponse) Reset() {
	*x = SettleWindowResponse{}
	mi := &file_settlement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleWindowResponse) ProtoMessage() {}

func (x *SettleWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleWindowResponse.ProtoReflect.Descriptor instead.
func (*SettleWindowResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{2}
}

func (x *SettleWindowResponse) GetPositions() []*NetPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *SettleWindowResponse) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type NetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bic           string                 `protobuf:"bytes,1,opt,name=bic,proto3" json:"bic,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // net amount; positive = receives, negative = pays
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetPosition) Reset() {
	*x = NetPosition{}
	mi := &file_settlement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetPosition) ProtoMessage() {}

func (x *NetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetPosition.ProtoReflect.Descriptor instead.
func (*NetPosition) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{3}
}

func (x *NetPosition) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *NetPosition) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NetPosition) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type NetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetPositionRequest) Reset() {
	*x = NetPositionRequest{}
	mi := &file_settlement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetPositionRequest) ProtoMessage() {}

func (x *NetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetPositionRequest.ProtoReflect.Descriptor instead.
func (*NetPositionRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{4}
}

func (x *NetPositionRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type NetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*NetPosition         `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetPositionResponse) Reset() {
	*x = NetPositionResponse{}
	mi := &file_settlement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetPositionResponse) ProtoMessage() {}

func (x *NetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetPositionResponse.ProtoReflect.Descriptor instead.
func (*NetPositionResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{5}
}

func (x *NetPositionResponse) GetPositions() []*NetPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_settlement_proto protoreflect.FileDescriptor

const file_settlement_proto_rawDesc = "" +
	"\n" +
	"\x10settlement.proto\x12\tswitch.v1\x1a\rpayment.proto\"H\n" +
	"\rSettlementAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\twindow_id\x18\x02 \x01(\tR\bwindowId\"2\n" +
	"\x13SettleWindowRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\"i\n" +
	"\x14SettleWindowResponse\x124\n" +
	"\tpositions\x18\x01 \x03(\v2\x16.switch.v1.NetPositionR\tpositions\x12\x1b\n" +
	"\twindow_id\x18\x02 \x01(\tR\bwindowId\"S\n" +
	"\vNetPosition\x12\x10\n" +
	"\x03bic\x18\x01 \x01(\tR\x03bic\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"1\n" +
	"\x12NetPositionRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\"K\n" +
	"\x13NetPositionResponse\x124\n" +
	"\tpositions\x18\x01 \x03(\v2\x16.switch.v1.NetPositionR\tpositions2\xf4\x01\n" +
	"\n" +
	"Settlement\x12C\n" +
	"\x13SubmitForSettlement\x12\x12.switch.v1.Payment\x1a\x18.switch.v1.SettlementAck\x12O\n" +
	"\fSettleWindow\x12\x1e.switch.v1.SettleWindowRequest\x1a\x1f.switch.v1.SettleWindowResponse\x12P\n" +
	"\x0fGetNetPositions\x12\x1d.switch.v1.NetPositionRequest\x1a\x1e.switch.v1.NetPositionResponseB*Z(switch/api/proto/settlement;settlementpbb\x06proto3"

var (
	file_settlement_proto_rawDescOnce sync.Once
	file_settlement_proto_rawDescData []byte
)

func file_settlement_proto_rawDescGZIP() []byte {
	file_settlement_proto_rawDescOnce.Do(func() {
		file_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)))
	})
	return file_settlement_proto_rawDescData
}

var file_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_settlement_proto_goTypes = []any{
	(*SettlementAck)(nil),        // 0: switch.v1.SettlementAck
	(*SettleWindowRequest)(nil),  // 1: switch.v1.SettleWindowRequest
	(*SettleWindowResponse)(nil), // 2: switch.v1.SettleWindowResponse
	(*NetPosition)(nil),          // 3: switch.v1.NetPosition
	(*NetPositionRequest)(nil),   // 4: switch.v1.NetPositionRequest
	(*NetPositionResponse)(nil),  // 5: switch.v1.NetPositionResponse
	(*payment.Payment)(nil),      // 6: switch.v1.Payment
}
var file_settlement_proto_depIdxs = []int32{
	3, // 0: switch.v1.SettleWindowResponse.positions:type_name -> switch.v1.NetPosition
	3, // 1: switch.v1.NetPositionResponse.positions:type_name -> switch.v1.NetPosition
	6, // 2: switch.v1.Settlement.SubmitForSettlement:input_type -> switch.v1.Payment
	1, // 3: switch.v1.Settlement.SettleWindow:input_type -> switch.v1.SettleWindowRequest
	4, // 4: switch.v1.Settlement.GetNetPositions:input_type -> switch.v1.NetPositionRequest
	0, // 5: switch.v1.Settlement.SubmitForSettlement:output_type -> switch.v1.SettlementAck
	2, // 6: switch.v1.Settlement.SettleWindow:output_type -> switch.v1.SettleWindowResponse
	5, // 7: switch.v1.Settlement.GetNetPositions:output_type -> switch.v1.NetPositionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_settlement_proto_init() }
func file_settlement_proto_init() {
	if File_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_proto_goTypes,
		DependencyIndexes: file_settlement_proto_depIdxs,
		MessageInfos:      file_settlement_proto_msgTypes,
	}.Build()
	File_settlement_proto = out.File
	file_settlement_proto_goTypes = nil
	file_settlement_proto_depIdxs = nil
}
