// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: settlement.proto

package settlementpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	payment "switch/api/proto/payment"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Settlement_SubmitForSettlement_FullMethodName = "/switch.v1.Settlement/SubmitForSettlement"
	Settlement_SettleWindow_FullMethodName        = "/switch.v1.Settlement/SettleWindow"
	Settlement_GetNetPositions_FullMethodName     = "/switch.v1.Settlement/GetNetPositions"
)

// SettlementClient is the client API for Settlement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettlementClient interface {
	// Submit a completed payment for net settlement.
	SubmitForSettlement(ctx context.Context, in *payment.Payment, opts ...grpc.CallOption) (*SettlementAck, error)
	// Trigger settlement of the current window.
	SettleWindow(ctx context.Context, in *SettleWindowRequest, opts ...grpc.CallOption) (*SettleWindowResponse, error)
	// Get net positions for the current window.
	GetNetPositions(ctx context.Context, in *NetPositionRequest, opts ...grpc.CallOption) (*NetPositionResponse, error)
}

type settlementClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlementClient(cc grpc.ClientConnInterface) SettlementClient {
	return &settlementClient{cc}
}

func (c *settlementClient) SubmitForSettlement(ctx context.Context, in *payment.Payment, opts ...grpc.CallOption) (*SettlementAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementAck)
	err := c.cc.Invoke(ctx, Settlement_SubmitForSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementClient) SettleWindow(ctx context.Context, in *SettleWindowRequest, opts ...grpc.CallOption) (*SettleWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleWindowResponse)
	err := c.cc.Invoke(ctx, Settlement_SettleWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementClient) GetNetPositions(ctx context.Context, in *NetPositionRequest, opts ...grpc.CallOption) (*NetPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetPositionResponse)
	err := c.cc.Invoke(ctx, Settlement_GetNetPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettlementServer is the server API for Settlement service.
// All implementations must embed UnimplementedSettlementServer
// for forward compatibility.
type SettlementServer interface {
	// Submit a completed payment for net settlement.
	SubmitForSettlement(context.Context, *payment.Payment) (*SettlementAck, error)
	// Trigger settlement of the current window.
	SettleWindow(context.Context, *SettleWindowRequest) (*SettleWindowResponse, error)
	// Get net positions for the current window.
	GetNetPositions(context.Context, *NetPositionRequest) (*NetPositionResponse, error)
	mustEmbedUnimplementedSettlementServer()
}

// UnimplementedSettlementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettlementServer struct{}

func (UnimplementedSettlementServer) SubmitForSettlement(context.Context, *payment.Payment) (*SettlementAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitForSettlement not implemented")
}
func (UnimplementedSettlementServer) SettleWindow(context.Context, *SettleWindowRequest) (*SettleWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleWindow not implemented")
}
func (UnimplementedSettlementServer) GetNetPositions(context.Context, *NetPositionRequest) (*NetPositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetPositions not implemented")
}
func (UnimplementedSettlementServer) mustEmbedUnimplementedSettlementServer() {}
func (UnimplementedSettlementServer) testEmbeddedByValue()                    {}

// UnsafeSettlementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettlementServer will
// result in compilation errors.
type UnsafeSettlementServer interface {
	mustEmbedUnimplementedSettlementServer()
}

func RegisterSettlementServer(s grpc.ServiceRegistrar, srv SettlementServer) {
	// If the following call panics, it indicates UnimplementedSettlementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Settlement_ServiceDesc, srv)
}

func _Settlement_SubmitForSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payment.Payment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServer).SubmitForSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settlement_SubmitForSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServer).SubmitForSettlement(ctx, req.(*payment.Payment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settlement_SettleWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServer).SettleWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settlement_SettleWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServer).SettleWindow(ctx, req.(*SettleWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settlement_GetNetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServer).GetNetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settlement_GetNetPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServer).GetNetPositions(ctx, req.(*NetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Settlement_ServiceDesc is the grpc.ServiceDesc for Settlement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Settlement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Settlement",
	HandlerType: (*SettlementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitForSettlement",
			Handler:    _Settlement_SubmitForSettlement_Handler,
		},
		{
			MethodName: "SettleWindow",
			Handler:    _Settlement_SettleWindow_Handler,
		},
		{
			MethodName: "GetNetPositions",
			Handler:    _Settlement_GetNetPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settlement.proto",
}
