// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: routing.proto

package routingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceBic      string                 `protobuf:"bytes,1,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestinationBic string                 `protobuf:"bytes,2,opt,name=destination_bic,json=destinationBic,proto3" json:"destination_bic,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Fee            int64                  `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	EstimatedMs    int32                  `protobuf:"varint,5,opt,name=estimated_ms,json=estimatedMs,proto3" json:"estimated_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *Route) GetDestinationBic() string {
	if x != nil {
		return x.DestinationBic
	}
	return ""
}

func (x *Route) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Route) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Route) GetEstimatedMs() int32 {
	if x != nil {
		return x.EstimatedMs
	}
	return 0
}

type FindRouteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceBic      string                 `protobuf:"bytes,1,opt,name=source_bic,json=sourceBic,proto3" json:"source_bic,omitempty"`
	DestinationBic string                 `protobuf:"bytes,2,opt,name=destination_bic,json=destinationBic,proto3" json:"destination_bic,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindRouteRequest) Reset() {
	*x = FindRouteRequest{}
	mi := &file_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteRequest) ProtoMessage() {}

func (x *FindRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteRequest.ProtoReflect.Descriptor instead.
func (*FindRouteRequest) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{1}
}

func (x *FindRouteRequest) GetSourceBic() string {
	if x != nil {
		return x.SourceBic
	}
	return ""
}

func (x *FindRouteRequest) GetDestinationBic() string {
	if x != nil {
		return x.DestinationBic
	}
	return ""
}

func (x *FindRouteRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type FindRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRouteResponse) Reset() {
	*x = FindRouteResponse{}
	mi := &file_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteResponse) ProtoMessage() {}

func (x *FindRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteResponse.ProtoReflect.Descriptor instead.
func (*FindRouteResponse) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{2}
}

func (x *FindRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type AddRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	mi := &file_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{3}
}

func (x *AddRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type AddRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRouteResponse) Reset() {
	*x = AddRouteResponse{}
	mi := &file_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteResponse) ProtoMessage() {}

func (x *AddRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteResponse.ProtoReflect.Descriptor instead.
func (*AddRouteResponse) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{4}
}

var File_routing_proto protoreflect.FileDescriptor

const file_routing_proto_rawDesc = "" +
	"\n" +
	"\rrouting.proto\x12\tswitch.v1\"\xa0\x01\n" +
	"\x05Route\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x01 \x01(\tR\tsourceBic\x12'\n" +
	"\x0fdestination_bic\x18\x02 \x01(\tR\x0edestinationBic\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x03R\x03fee\x12!\n" +
	"\festimated_ms\x18\x05 \x01(\x05R\vestimatedMs\"v\n" +
	"\x10FindRouteRequest\x12\x1d\n" +
	"\n" +
	"source_bic\x18\x01 \x01(\tR\tsourceBic\x12'\n" +
	"\x0fdestination_bic\x18\x02 \x01(\tR\x0edestinationBic\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\";\n" +
	"\x11FindRouteResponse\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.switch.v1.RouteR\x05route\"9\n" +
	"\x0fAddRouteRequest\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.switch.v1.RouteR\x05route\"\x12\n" +
	"\x10AddRouteResponse2\x96\x01\n" +
	"\aRouting\x12F\n" +
	"\tFindRoute\x12\x1b.switch.v1.FindRouteRequest\x1a\x1c.switch.v1.FindRouteResponse\x12C\n" +
	"\bAddRoute\x12\x1a.switch.v1.AddRouteRequest\x1a\x1b.switch.v1.AddRouteResponseB$Z\"switch/api/proto/routing;routingpbb\x06proto3"

var (
	file_routing_proto_rawDescOnce sync.Once
	file_routing_proto_rawDescData []byte
)

func file_routing_proto_rawDescGZIP() []byte {
	file_routing_proto_rawDescOnce.Do(func() {
		file_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)))
	})
	return file_routing_proto_rawDescData
}

var file_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_routing_proto_goTypes = []any{
	(*Route)(nil),             // 0: switch.v1.Route
	(*FindRouteRequest)(nil),  // 1: switch.v1.FindRouteRequest
	(*FindRouteResponse)(nil), // 2: switch.v1.FindRouteResponse
	(*AddRouteRequest)(nil),   // 3: switch.v1.AddRouteRequest
	(*AddRouteResponse)(nil),  // 4: switch.v1.AddRouteResponse
}
var file_routing_proto_depIdxs = []int32{
	0, // 0: switch.v1.FindRouteResponse.route:type_name -> switch.v1.Route
	0, // 1: switch.v1.AddRouteRequest.route:type_name -> switch.v1.Route
	1, // 2: switch.v1.Routing.FindRoute:input_type -> switch.v1.FindRouteRequest
	3, // 3: switch.v1.Routing.AddRoute:input_type -> switch.v1.AddRouteRequest
	2, // 4: switch.v1.Routing.FindRoute:output_type -> switch.v1.FindRouteResponse
	4, // 5: switch.v1.Routing.AddRoute:output_type -> switch.v1.AddRouteResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routing_proto_init() }
func file_routing_proto_init() {
	if File_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routing_proto_goTypes,
		DependencyIndexes: file_routing_proto_depIdxs,
		MessageInfos:      file_routing_proto_msgTypes,
	}.Build()
	File_routing_proto = out.File
	file_routing_proto_goTypes = nil
	file_routing_proto_depIdxs = nil
}
