// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: routing.proto

package routingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Routing_FindRoute_FullMethodName = "/switch.v1.Routing/FindRoute"
	Routing_AddRoute_FullMethodName  = "/switch.v1.Routing/AddRoute"
)

// RoutingClient is the client API for Routing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingClient interface {
	FindRoute(ctx context.Context, in *FindRouteRequest, opts ...grpc.CallOption) (*FindRouteResponse, error)
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteResponse, error)
}

type routingClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingClient(cc grpc.ClientConnInterface) RoutingClient {
	return &routingClient{cc}
}

func (c *routingClient) FindRoute(ctx context.Context, in *FindRouteRequest, opts ...grpc.CallOption) (*FindRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRouteResponse)
	err := c.cc.Invoke(ctx, Routing_FindRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRouteResponse)
	err := c.cc.Invoke(ctx, Routing_AddRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServer is the server API for Routing service.
// All implementations must embed UnimplementedRoutingServer
// for forward compatibility.
type RoutingServer interface {
	FindRoute(context.Context, *FindRouteRequest) (*FindRouteResponse, error)
	AddRoute(context.Context, *AddRouteRequest) (*AddRouteResponse, error)
	mustEmbedUnimplementedRoutingServer()
}

// UnimplementedRoutingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServer struct{}

func (UnimplementedRoutingServer) FindRoute(context.Context, *FindRouteRequest) (*FindRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRoute not implemented")
}
func (UnimplementedRoutingServer) AddRoute(context.Context, *AddRouteRequest) (*AddRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRoute not implemented")
}
func (UnimplementedRoutingServer) mustEmbedUnimplementedRoutingServer() {}
func (UnimplementedRoutingServer) testEmbeddedByValue()                 {}

// UnsafeRoutingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServer will
// result in compilation errors.
type UnsafeRoutingServer interface {
	mustEmbedUnimplementedRoutingServer()
}

func RegisterRoutingServer(s grpc.ServiceRegistrar, srv RoutingServer) {
	// If the following call panics, it indicates UnimplementedRoutingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Routing_ServiceDesc, srv)
}

func _Routing_FindRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServer).FindRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Routing_FindRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServer).FindRoute(ctx, req.(*FindRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Routing_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServer).AddRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Routing_AddRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Routing_ServiceDesc is the grpc.ServiceDesc for Routing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Routing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switch.v1.Routing",
	HandlerType: (*RoutingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindRoute",
			Handler:    _Routing_FindRoute_Handler,
		},
		{
			MethodName: "AddRoute",
			Handler:    _Routing_AddRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routing.proto",
}
